/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hairforyou.appointmentsystem;

/**
 *
 * @author lambe
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        hairForYouWhiteLogo = new javax.swing.JLabel();
        newClientLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        securityQuestionField = new javax.swing.JPasswordField();
        lastNameField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        addressLabel = new javax.swing.JLabel();
        emailAddressField = new javax.swing.JPasswordField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        securityQuestionLabel1 = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        roleField = new javax.swing.JPasswordField();
        usernameLabel1 = new javax.swing.JLabel();
        usernameField1 = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hairforyou/appointmentsystem/images/hair-for-you-interior.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminPanel.setBackground(new java.awt.Color(204, 204, 204));
        adminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hairForYouWhiteLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hairforyou/appointmentsystem/images/hair-for-you-logo-small.png"))); // NOI18N
        adminPanel.add(hairForYouWhiteLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        newClientLabel.setBackground(new java.awt.Color(255, 255, 255));
        newClientLabel.setFont(new java.awt.Font("Perpetua", 0, 21)); // NOI18N
        newClientLabel.setText("NEW ADMIN");
        adminPanel.add(newClientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, 30));

        questionLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        questionLabel.setText("What was the name of your first pet?");
        adminPanel.add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 320, 30));

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name:");
        adminPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name:");
        adminPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        securityQuestionField.setBackground(new java.awt.Color(204, 204, 204));
        securityQuestionField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        securityQuestionField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(securityQuestionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 230, -1));

        lastNameField.setBackground(new java.awt.Color(204, 204, 204));
        lastNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lastNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, -1));

        confirmPasswordField.setBackground(new java.awt.Color(204, 204, 204));
        confirmPasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        confirmPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 170, -1));

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLabel.setText("Email address: ");
        adminPanel.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        emailAddressField.setBackground(new java.awt.Color(204, 204, 204));
        emailAddressField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        emailAddressField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(emailAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, -1));

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNumberLabel.setText("Phone number:");
        adminPanel.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        phoneNumberField.setBackground(new java.awt.Color(204, 204, 204));
        phoneNumberField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        phoneNumberField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });
        adminPanel.add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabel.setText("Password:");
        adminPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        passwordField.setBackground(new java.awt.Color(204, 204, 204));
        passwordField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 230, -1));

        confirmPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password:");
        adminPanel.add(confirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        firstNameField.setBackground(new java.awt.Color(204, 204, 204));
        firstNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        firstNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 230, -1));

        submitButton.setBackground(new java.awt.Color(51, 102, 255));
        submitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setBorderPainted(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        adminPanel.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 90, 30));

        securityQuestionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        securityQuestionLabel1.setText("Security Question:");
        adminPanel.add(securityQuestionLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        Role.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Role.setText("Role:");
        adminPanel.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        roleField.setBackground(new java.awt.Color(204, 204, 204));
        roleField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        roleField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        adminPanel.add(roleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, -1));

        usernameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLabel1.setText("Username:");
        adminPanel.add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        usernameField1.setBackground(new java.awt.Color(204, 204, 204));
        usernameField1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        usernameField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 51, 255)));
        usernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField1ActionPerformed(evt);
            }
        });
        adminPanel.add(usernameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 230, -1));

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        adminPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 90, 30));

        getContentPane().add(adminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void usernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Role;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPasswordField emailAddressField;
    private javax.swing.JPasswordField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel hairForYouWhiteLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel newClientLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField phoneNumberField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JPasswordField roleField;
    private javax.swing.JPasswordField securityQuestionField;
    private javax.swing.JLabel securityQuestionLabel1;
    private javax.swing.JButton submitButton;
    private javax.swing.JPasswordField usernameField1;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
