/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hairforyou.appointmentsystem;

/**
 *
 * @author manoklm
 */
public class ClientMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentGUI2
     */
    public ClientMenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of thi s method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hairForYouBlackIconLabel = new javax.swing.JLabel();
        welcomeBackLabel = new javax.swing.JLabel();
        scheduleAppointment = new javax.swing.JButton();
        closeMenu = new javax.swing.JButton();
        viewAppointment2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hairForYouBlackIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hairforyou/appointmentsystem/images/hair-for-you-logo.png"))); // NOI18N
        jPanel1.add(hairForYouBlackIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 70));

        welcomeBackLabel.setBackground(new java.awt.Color(0, 102, 204));
        welcomeBackLabel.setFont(new java.awt.Font("Perpetua", 0, 30)); // NOI18N
        welcomeBackLabel.setText("CLIENT MENU");
        welcomeBackLabel.setToolTipText("1");
        jPanel1.add(welcomeBackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        scheduleAppointment.setBackground(new java.awt.Color(153, 153, 153));
        scheduleAppointment.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        scheduleAppointment.setText("Schedule an Appointment");
        scheduleAppointment.setBorderPainted(false);
        scheduleAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleAppointmentActionPerformed(evt);
            }
        });
        jPanel1.add(scheduleAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, 30));

        closeMenu.setBackground(new java.awt.Color(153, 153, 153));
        closeMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        closeMenu.setText("Close Menu");
        closeMenu.setBorderPainted(false);
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        jPanel1.add(closeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, 30));

        viewAppointment2.setBackground(new java.awt.Color(153, 153, 153));
        viewAppointment2.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        viewAppointment2.setText("View Appointments");
        viewAppointment2.setBorderPainted(false);
        viewAppointment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppointment2ActionPerformed(evt);
            }
        });
        jPanel1.add(viewAppointment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 30));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateLabel.setText("Date:");
        jPanel2.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        firstNameField.setBackground(new java.awt.Color(153, 153, 153));
        firstNameField.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        firstNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 370, 350));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleAppointmentActionPerformed
    }//GEN-LAST:event_scheduleAppointmentActionPerformed

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed
    }//GEN-LAST:event_closeMenuActionPerformed

    private void viewAppointment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppointment2ActionPerformed
    }//GEN-LAST:event_viewAppointment2ActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed

    }//GEN-LAST:event_firstNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeMenu;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel hairForYouBlackIconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton scheduleAppointment;
    private javax.swing.JButton viewAppointment2;
    private javax.swing.JLabel welcomeBackLabel;
    // End of variables declaration//GEN-END:variables
}
