/**
 *
 * @author manoklm
 */
package com.hairforyou.appointmentsystem;

import java.awt.Toolkit;
import java.awt.Dimension;

public class UserManager extends javax.swing.JFrame {

    public UserManager() {
        initComponents();
        buttonHover();
        centerPanel();
        setVisible(true);
    }

    /**
     * Creates new form UserManager
     */

    /**y2
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userManagerPanel = new javax.swing.JPanel();
        hairForYouLogo = new javax.swing.JLabel();
        createUserLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        iAmALabel = new javax.swing.JLabel();
        clientButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userManagerPanel.setBackground(new java.awt.Color(255, 255, 255));
        userManagerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hairForYouLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hairforyou/appointmentsystem/images/hair-for-you-logo-small.png"))); // NOI18N
        userManagerPanel.add(hairForYouLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        createUserLabel.setBackground(new java.awt.Color(255, 255, 255));
        createUserLabel.setFont(new java.awt.Font("Perpetua", 0, 21)); // NOI18N
        createUserLabel.setText("CREATE USER");
        userManagerPanel.add(createUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 30));

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        userManagerPanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 30));

        iAmALabel.setBackground(new java.awt.Color(0, 0, 0));
        iAmALabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        iAmALabel.setText("I am a(n):");
        userManagerPanel.add(iAmALabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        clientButton.setBackground(new java.awt.Color(0, 255, 0));
        clientButton.setText("Client");
        clientButton.setBorderPainted(false);
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        userManagerPanel.add(clientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, 30));

        adminButton.setBackground(new java.awt.Color(0, 102, 255));
        adminButton.setText("Admin");
        adminButton.setBorderPainted(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        userManagerPanel.add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hairforyou/appointmentsystem/images/hair-for-you-interior.png"))); // NOI18N
        userManagerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 280));

        getContentPane().add(userManagerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void centerPanel() {
        // Get the screen size
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calculate the center position of the screen
        int centerX = (int) ((screenSize.getWidth() - getWidth()) / 2);
        int centerY = (int) ((screenSize.getHeight() - getHeight()) / 2);

        // Set the position of the frame to the center of the screen
        setLocation(centerX, centerY);

        // Set the position of the frame to the center of the screen
        setLocation(centerX, centerY);
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        new NewAdminGUI();
        this.dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        new NewClientGUI();
        this.dispose();
    }//GEN-LAST:event_clientButtonActionPerformed
    public void buttonHover() {
        clientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        });

        adminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        });

        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        });
    /**
     * @param args the command line arguments
     */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clientButton;
    private javax.swing.JLabel createUserLabel;
    private javax.swing.JLabel hairForYouLogo;
    private javax.swing.JLabel iAmALabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel userManagerPanel;
    // End of variables declaration//GEN-END:variables
}

